[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gradjoeng"
version = "0.1.0"
description = "Live view of Gradient CI events"
requires-python = ">=3.12"
dependencies = ["moderngl", "pygame-ce", "websockets"]

[project.scripts]
gradjoeng = "gradjoeng.main:main"

[tool.setuptools.package-data]
gradjoeng = ["shaders/*"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["gradjoeng*"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
